export const vinhosJson = [
    {
        id: 1,
        title: "Arturo Cabernet Sauvignon",
        type: "Suaves",
        description: ``,
        detailDescription:[
            
        ],
        topics: "",
        harmonization: "",
        image: "./public/img/garrafas/Vinhos Suaves/arturo suave.png",
        url: "",
        grape: "",
        country: "Brasil",
        region: "",
        productor: "",
        safra: "",
        alcolic: "",
        volume: "750ml",
        selected: true,
    },
    {
        id: 2,
        title: "Arturo Cabernet Sauvignon",
        type: "Tintos",
        description: ``,
        detailDescription:[
            
        ],
        topics: "",
        harmonization: "",
        image: "./public/img/garrafas/Vinhos Tintos/arturo seco.png",
        url: "",
        grape: "",
        country: "Brasil",
        region: "",
        productor: "",
        safra: "",
        alcolic: "",
        volume: "750ml",
        selected: true,
    }, 
    {
        id: 3,
        title: "Natural Delama Brut",
        type: "Vinho Espumante",
        description: `
          Elaborado pelo método charmat, apresenta elegante perlage, fineza aromática, boa cremosidade, excelente equilíbrio e persistência.
        `,
        detailDescription:[
            "Iniciado em 2024, este projeto nasceu da seleção criteriosa das melhores uvas para a criação dos novos espumantes Arturo Vinhos. O lançamento está previsto para o final de 2025 — um brinde especial a mais um passo importante da nossa história.",
            "A região escolhida foi Garibaldi, reconhecida por seu terroir e excelência na produção de espumantes premium. Unimos essa tradição à nossa filosofia de valorizar enólogos talentosos — ainda pouco conhecidos, mas com enorme dedicação, técnica e paixão pelo que fazem — garantindo que cada detalhe, do vinhedo à taça, seja tratado com o máximo cuidado.",
        ],
        topics: "Produção limitada (lotes pequenos e controlados); Foco na qualidade, não na quantidade; Uvas rigorosamente selecionadas e vinificadas em pequenas autoclaves; Enólogo promissor; Região e vinhedo: Garibaldi (melhores espumantes do Brasil); Público-alvo: hotéis, restaurantes e lojas especializadas; Exclusividade comercial (não competimos com lojas online de massa); Linha de elaboração própria.",
        harmonization: "A região escolhida foi Garibaldi, reconhecida por seu terroir e excelência na produção de espumantes premium. Unimos essa tradição à nossa filosofia de valorizar enólogos talentosos — ainda pouco conhecidos, mas com enorme dedicação, técnica e paixão pelo que fazem — garantindo que cada detalhe, do vinhedo à taça, seja tratado com o máximo cuidado.",
        image: "./public/img/garrafas/Espumantes/delama-brut.png",
        url: "https://www.botecodovinho.com.br/produto/delama-espumante-natural-brut-750ml/",
        grape: "Chardonnay, Riesling Itálico e Prosecco",
        country: "Brasil",
        region: "Garibaldi",
        productor: "Vinicola São Luis",
        safra: "2025",
        alcolic: "12.5%",
        volume: "750ml",
        selected: true,
    },
    {
        id: 4,
        title: "Florada dos Campos Moscatel",
        type: "Espumante",
        description: ``,
        detailDescription:[
        ],
        topics: "",
        harmonization: "",
        image: "./public/img/garrafas/Espumantes/moscatel.png",
        url: "",
        grape: "",
        country: "",
        region: "",
        productor: "",
        safra: "",
        alcolic: "12.5%",
        volume: "",
        selected: true,
    },
    {
        id: 5,
        title: "Florada Dos Campos",
        type: "Vinho Branco",
        description: ``,
        detailDescription:[],
        topics: "",
        harmonization: "",
        image: "./public/img/garrafas/Vinhos Brancos/florada-campos.png",
        url: "",
        grape: "",
        country: "",
        region: "",
        productor: "",
        safra: "",
        alcolic: "",
        volume: "",
        selected: true,
    },

    {
        id: 6,
        title: "Delaso",
        type: "Vinho Suave",
        description: `
        `,
        detailDescription:[
        ],
        topics: "",
        harmonization: "",
        image: "./public/img/garrafas/Vinhos Suaves/delaso.png",
        url: "",
        grape: "Chardonnay, Riesling Itálico e Prosecco",
        country: "Brasil",
        region: "Garibaldi",
        productor: "Vinicola São Luis",
        safra: "2025",
        alcolic: "12.5%",
        volume: "750ml",
        selected: true,
    },
];
